<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Information has not been added yet.' => 'Информация еще не добавлена.',
    'Not found.' => 'Не найдено.',
    'Active' => 'Активен',
    'Answer' => 'Ответ',
    'Answers' => 'Ответы',
    'Are you sure you want to delete this answer?' => 'Вы действительно хотите удалить этот ответ?',
    'Are you sure you want to delete this category?' => 'Вы действительно хотите удалить эту категорию?',
    'Are you sure you want to delete this hint?' => 'Вы действительно хотите удалить эту подсказку?',
    'Are you sure you want to delete this news?' => 'Вы действительно хотите удалить эту новость?',
    'Are you sure you want to delete this page?' => 'Вы действительно хотите удалить эту страницу?',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Code' => 'Код',
    'Content' => 'Контент',
    'Create' => 'Создать',
    'Create News' => 'Создать новость',
    'Create answer' => 'Создать ответ',
    'Create category' => 'Создать категорию',
    'Create hint' => 'Создать подсказку',
    'Create news' => 'Создать новость',
    'Create page' => 'Создать страницу',
    'Created' => 'Создано',
    'Delete' => 'Удалить',
    'Draft' => 'Черновик',
    'Faq' => 'ЧаВо',
    'Hint' => 'Подсказка',
    'Hints' => 'Подсказки',
    'ID' => '#',
    'Icon' => 'Значок',
    'News' => 'Новости',
    'Page' => 'Страница',
    'Pages' => 'Страницы',
    'Question' => 'Вопрос',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Slug' => 'Url',
    'Status' => 'Статус',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update category' => 'Обновить категорию',
    'Update hint' => 'Обновить подсказку',
    'Update news' => 'Обновить новость',
    'Update page' => 'Обновить страницу',
    'Updated' => 'Обновлено',
];
